### ISSUE TITLE
Regression Test Checklist

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#140]
After OS Patching or any other scenario where validation of running application is needed, we should run a regression test.  This can be manual checklist to start with automating any steps as an end goal.
- [x] create manual checklist
- [x] determine what could be scripted
- [x] include in the EZID Operations page

**Comment by rushirajnenuji** [comment]
Tests performed after OS Patching: 

- [ ] EZID app status on the server
- [ ] EZID app logs
- [ ] Status of background jobs
- [ ] (prod): LC status
- [ ] UI > search: random keyword
- [ ] mint - sample DOI and ARK on test shoulder

**Comment by datadavev** [comment]
Add these steps to the confluence ops docs
