### ISSUE TITLE
EZID Stage 3 upgrade checklist

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#257]
See also #147 

## Pre-Upgrade (prepare for upgrade)

- [x] Create snapshot of production database. Ensure that the RDS instance has sufficient resources for supporting the migration process. (Ashley)
- [x] Change passwords for database to stage passwords (Ashley)
- [x] Update SSM parameters to point to new RDS instance
- [x] Verify operation of stage 3 prior to wiping (Dave, Roger, Rushi)
- [x] Copy scripts and other things to preserve out of `ezid` account (Roger)
- [x] Shutdown ezid app and services
- [x] Wipe everything under `ezid` account on the stage3 

(reminder for production- ensure all the queues are caught up)

## Upgrade (upgrade database and application)

- [x] Install new code base (Ashley)
- [x] Copy minter databases from production to new instance (Roger)
- [x] Verify configuration setting for database access, admin account (Roger)
- [x] Perform database migration (total time ~6hrs)
    - [ ] Install additional packages needed only for the migration
       ```
       $ pip install mysql.connector
       ```
    - [ ] Temporarily set DB user to eziddba with appropriate pw for login in settings.py
    - [ ] Run migration through Tmux shell on stg-py3
    - [ ] Set environment variables for database access. Manual step to set env vars directly (Roger)
    - [ ] Run the script `migrate_db_to_py3/run-migration.py` This process runs several tasks against the database and will take several hours in total. (Roger)
    - [ ] Set DB user to ezidrw with appropriate pw in settings.py
- [x] Startup EZID app and background jobs
- [x] Verify load balancer configuration is pointing to the correct host
- [ ] Initial sanity checks of operation
    - [ ] Verify anonymous ARK mint
    - [ ] Verify admin login
    - [ ] Verify admin ARK mint
    - [ ] Verify admin view groups, correct number of entries
- [ ] Start linkchecker, background jobs
    - [ ] Verify DataCite DOI minting, search
    - [ ] Verify Crossref DOI minting, search
    - [ ] Verify ARK minting, search
- [ ] Comprehensive automated and manual tests (note that some searches may be slow at this point)

## Post-Upgrade part 2 (verify operation)

- [ ] Notify general availability
- [ ] Continue adding additional indexes to improve search performance
- [ ] Continue testing basic search, login, minting with the application to verify expected functionality
- [ ] Verify Nagios monitoring of background tasks

## Post-Upgrade part 3

- [ ] Notify intent of change for ezid stage
- [ ] Request IAS to perform service cutover of `ezid-stg.cdlib.org`  by swapping ec2 instances in ALB target group. See **ALB Cutover Instructions** below for details.
- [ ] Notify of change

## ALB Cutover Instructions

Request IAS team to do the following:
- deregister host `uc3-ezidui02x2-stg` from TargetGroup `uc3-ezidui-py3-stg-tg`
- deregister host `uc3-ezidui01x2-stg` from TargetGroup `uc3-ezidui-stg-tg`
- register host `uc3-ezidui02x2-stg` in TargetGroup `uc3-ezidui-stg-tg`
