### ISSUE TITLE
resolver v3.1.0rc2 checklist

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#382]
Actions targeting v3.1.0 RC2 in support of resolver functionality.

- [x] log_level template variable not set in ssm for dev environment, set default in template
- [x] Format created and updated dates presented in inflection response
- [x] Adjust ANVL property names to align with N2T
- [x] Verify inflection response for records that have datacite metadata attached to ark ids
- [x] Adjust template variable `resolver_ark` to point to the EZID instance instead of N2T

Changes are being made in the `resolve-300` branch, RC tags are made on this branch until all known issues are resolved.

**Comment by datadavev** [comment]
Can set `resolver_ark` to `ezid_base_url`, which contains the outward facing service address.

**Comment by datadavev** [comment]
N2T appears to perform some kinds of undocumented profile mapping to generate the ANVL response. Full consistency with N2T ANVL response seems out of scope, though can be revisited if there is demand.
