### ISSUE TITLE
[MAINTENANCE] Unify N2T and EZID Resolver Logic Post-Migration

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#652]
**Service/repository**
EZID Resolver

**Describe the current state/issue**

As the N2T migration nears completion, the final state of N2T's resolver and that implemented in EZID have somewhat diverged.

**Describe the desired state/solution**

The logic for these should be unified or kept consistent to the largest degree possible moving forward.

**Tasks**

- [ ] Confer with Dave on the current state of the N2T resolver, documenting any differences from the EZID implementation.
- [ ] Define total possible scope of alignment and required changes to EZID resolver.
- [ ] Update EZID resolver logic relative to the above.
- [ ] Define and document plan for updating logic in both services (to the extent possible) relative to changes in N2T
