### ISSUE TITLE
[RESEARCH] Research rate limiting/blocking based on referrer in AWS WAF

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#682]
## Background
We should investigate additional traffic control measures based on the HTTP referrer header. Specifically, we want to block or limit requests to routes such as password reset and account login that do not come from our own domain.

## Objective
Research options for using WAF to block or limit traffic based on the referrer header. .

## Tasks

-  [ ] Investigate how AWS WAF handles the referrer header.
- [ ] Investigate whether we can create a rule in AWS WAF that inspects the referrer header.

If we can manage traffic in WAF based on the referrer:
  -  [ ] Define conditions for blocking or allowing traffic based on the referrer.
  - [ ] Ensure that the rule is flexible enough to handle all EZID application referrer patterns.
  - [ ] Test the rule to confirm it works as expected.
  - [ ] Document the entire process, including:
    - Steps to create and configure the rule.
    - Details on modifying the rule for different referrer patterns.
    - Testing procedures and results.

## References
- [AWS WAF Documentation](https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html)
- [AWS WAF Rule Creation](https://docs.aws.amazon.com/waf/latest/developerguide/classic-web-acl-rules-creating.html)
- [AWS WAF Rule Testing](https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-testing.html)

**Comment by adambuttrick** [comment]
I discussed this issue briefly with Liz Krznarich from DataCite. She indicated that the AWS load balancers typically do not include the referrer information from the requests such that this would be accessible to the WAF for rate limiting or blocking. We should verify. Her recommendation was that we consider whether the routes that are only used by the application could be moved inside a VPC, such that they're not surfaced or publicly accessible to anything other than the application itself.

**Comment by jsjiang** [comment]
It looks like 

```
