### ISSUE TITLE
[DATA] DOI Purge and Cleanup of FAIR Island Project

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#685]
## Data Task Type
DOI Management, Shoulder, and Account Cleanup

## Describe the data task needed
Metadata Game Changers wants to manage DOIs created as part of the FAIR Island project outside of EZID going forward. We need to transfer the corresponding prefix out of EZID, purge the set of DOIs and clean up the related shoulder and accounts.

## Task list
- [x] 1. Initiate prefix transfer with DataCite
- [x] 2. Disconnect shoulder from user account
- [ ] 3. Process DOI deletions
- [ ] 4. Account cleanup
  - [ ] Deactivate/delete the FAIR Island shoulder
  - [ ] Delete the Fair Island user account

## Expected outcome
All FAIR Island DOIs removed from EZID, shoulder deactivated, and Fair Island user accounts deleted.

## Additional information
- DOIs to be purged: 
[20240723_FAIR_Island_DOIS.csv](https://github.com/user-attachments/files/16351801/20240723_FAIR_Island_DOIS.csv)
