### ISSUE TITLE
[EPIC] Create New OpenSearch Index from Alias

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#754]
## Description
Following from https://github.com/CDLUC3/ezid/issues/729, we've decided to implement a process to create and switch to a new OpenSearch index from an alias.

## Tasks
- [x] Create an `alias` to our currently in use index like have `ezid-app-search-dev-alias` point to our current index of `ezid-app-search-dev`.
- [x] Update SSM to use this alias in the configuration (Ashley documented how to do this in Confluence).  There will be no visible change in behavior as long as done carefully and with correct name for the alias. It will begin using the alias on the next successful deploy when SSM values get re-written to the `settings`.
- [x] Create a new index that is not in use by the search itself (can be done automatically when indexing starts from the management opensearch-indexing script so long as a different index name is given in settings).
- [x] To do indexing against a different OpenSearch index from the one in use by search:
  - [x] Check out the code to a directory such as `~/tmp`.
  - [x] Copy the `settings.py` from the `~/ezid/settings` in the real app to the correct place in the `tmp` checkout.
  - [x] Modify the index name in settings to be different from the index in use by the search system. (example `ezid-app-search-dev2`)
  - [x] Also modify this file and search for log levels of DEBUG and change them to ERROR.  Otherwise this script writes out an outrageous amount to log files in some circumstances. It didn't used to do this, but seems like it now does (we're not quite sure why something in the environment seems to have changed).
  - [x] Run `python manange.py opensearch-update` and let it finish indexing (restart as needed from the middle if it dies or gets killed or the server gets rebooted before it finishes).  This script will automatically create the index if it doesn't exist already.
- [x] After indexing completes once
  - [x] Run indexing again for items updated since the time it started running the first time for example `python -u manage.py opensearch-update --updated_since 2024-10-27T00:00:00Z 2>&1 >  ../logs/opensearch_indexing.log` Give some extra time overlap if you want.  (The updateTime is now corrected in code for the link checker and is incorporated into develop/main and should be deployed shortly.  The code with correct update times needs to be running before we run indexing.)
- [ ] Putting the new index into use by search.
  - [x] Run incremental re-indexing (like the step above) for items since the last update so there are very few changed items.
  - [x] Be sure that application is using the `alias` (can be done far ahead of this step, but a deploy with SSM configured for the alias will also do this).
  - [x] Reconfigure the alias to point at the new index (can be done in the OpenSearch dashboard or using opensearch-util mgmt command).
  - [x] Run another incremental re-index to catch any items changed in the past few minutes--there will probably be only a few (like `python -u manage.py opensearch-update --updated_since 2024-10-27T00:00:00Z 2>&1 >  ../logs/opensearch_indexing.log`).
  - [x] Run the `opensearch-delete` management command (example `python -u manage.py opensearch-delete 2>&1 > ../logs/opensearch_delete.log`).  It will go through and cross-check identifiers which exist in the OpenSearch index but have been removed from the database.  It may take a while to run and check all IDs but there aren't all that many deletes and it caused no performance issues I could see when I ran it before.  (I don't think deleting large numbers of identifiers from EZID is a common occurrence since identifiers are supposed to be persistent and we avoid deletes.)
- [x] Once running successfully from the new index (that the alias points to), we can delete the old index which is now no longer in use.

## Dependencies
- Update code to ensure that the ezidapp_searchidentifier.updateTime is correctly updated any time the record is updated - https://github.com/CDLUC3/ezid/issues/752
- Storage increase for alias index

**Comment by sfisher** [comment]
I think I had a different detailed plan (in some other ticket which I lost now) but have changed my thinking of how to do things. I've been validating this on dev.

I was going to 1) reshuffle the names so that our Alias is the same index name we're using in SSM right now (which turns out to be tricky since can't rename things and the copy index processes are long/resource intensive); 2) copy index internally with OpenSearch copy commands; 3) update items as needed.  it turned out that this wasn't a great workflow for a lot of reasons, but mostly because the copy index commands make our entire opensearch node go slow and cause nagios errors.

My current thinking about the order of events is this, instead, and I'm testing it on dev to be sure it's feasible.

- [ ] Create an `alias` to our currently in use index like have `ezid-app-search-dev-alias` point to our current index of `ezid-app-search-dev`.
- [ ] Update SSM to use this alias in the configuration (Ashley documented how to do this in Confluence).  There will be no visible change in behavior as long as done carefully and with correct name for the alias. It will begin using the alias on the next successful deploy when SSM values get re-written to the `settings`.
- [ ] Create a new index that is not in use by the search itself (can be done automatically when indexing starts from the management opensearch-indexing script so long as a different index name is given in settings).
- [ ] To do indexing against a different OpenSearch index from the one in use by search:
  - [ ] Check out the code to a directory such as `~/tmp`.
  - [ ] Copy the `settings.py` from the `~/ezid/settings` in the real app to the correct place in the `tmp` checkout.
  - [ ] Modify the index name in settings to be different from the index in use by the search system. (example `ezid-app-search-dev2`)
  - [ ] Run `python manange.py opensearch-update` and let it finish indexing (restart as needed from the middle if it dies or gets killed or the server gets rebooted before it finishes).  This script will automatically create the index if it doesn't exist already.
- [ ] After indexing completes once
  - [ ] Run indexing again for items updated since the time it started running the first time in the step above give some extra overlap if you want (the updateTime is now corrected in code for the link checker and is incorporated into develop/main and should be deployed shortly).
- [ ] Putting the new index into use by search.
  - [ ] Run incremental re-indexing (like the step above) for items since the last update so there are very few changed items.
  - [ ] Be sure that application is using the `alias` (can be done far ahead of this step, but a deploy with SSM configured for the alias will also do this).
  - [ ] Reconfigure the alias to point at the new index (can be done in the OpenSearch dashboard or using opensearch-util mgmt command).
  - [ ] Run another incremental re-index to catch any items changed in the past few minutes there will probably be only a few.
  - [ ] Run the `opensearch-delete` management command.  It will go through and cross-check identifiers which exist in the OpenSearch index but have been removed from the database.  It may take a while to run and check all IDs but there aren't all that many deletes and it caused no performance issues when I tested before.  (I don't think deleting large numbers of identifiers from EZID is a common occurance since identifiers are supposed to be persistent.)
- Profit!

**Comment by sfisher** [comment]
Currently have been indexing into new dev index from the database for about a day.  OpenSearch went away for a bit sometime last night, but I restarted indexing this morning. It does not seem to cause issues with slowness on the node to index this way (Copying indexes internally with OpenSearch does seem to degrade node performance.)

**Comment by sfisher** [comment]
FOR development:

We ran out of space last week and I was able to free some since we had an index that wasn't deleted.

I managed to get the index to complete over the weekend. We ran out of space again this morning because of log processing.

Ashley cleared up some space.  I was able to do incremental indexing (I don't think any were added) and switch the index and now running the delete script which looks for items that exist in the index but not the database.

I think it's good for development.  I guess next is to move on to stage.
