### ISSUE TITLE
[DATA] Pull User Emails for DOI Shoulders and Prefixes with Records Using Deprecated Schema Versions

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#766]
## Describe the data task needed
As described in #540, we need to retrieve all user emails associated with each DOI shoulder or prefix that corresponds to records with old DataCite schema versions. For shoulders present in the EZID database, we'll pull emails based on the shoulder. For those not in the database, we'll attempt to retrieve based on the DOI prefix.

## Task list
- [x] 1. Query EZID database for each unique DOI shoulder associated with old schema versions
- [x] 2. For shoulders found in the database:
  - [x] Retrieve associated user emails
- [x] 3. For shoulders not found in the database:
  - [x] Query using the DOI prefix instead
  - [x] Retrieve associated user emails if found
- [x] 4. Compile a list of all retrieved emails and save in Google Drive
- [x] 5. Document any prefixes for which no data was found in EZID
- [x] 6. Cross-reference the retrieved emails with [exported shoulder report files](https://drive.google.com/drive/u/2/folders/1pWbTvWoEjbYCbW8YGfLgwH2bPOMiapBS)
- [x] 7. Notify users by email of intent to update.

## Additional information
- Total unique DOI prefixes: 56
- Prefixes confirmed in EZID shoulder table: 22
- Some prefixes may have been created outside of EZID. In such cases, we have no responsibility to update.

## Unique shoulders to process:
'doi:10.13022/M3', 'doi:10.15144/LT', 'doi:10.15144/MK', 'doi:10.15144/PL', 'doi:10.15782/D6', 'doi:10.18118/G6', 'doi:10.18739/A2', 'doi:10.21224/P4', 'doi:10.21228/M8', 'doi:10.21229/M9', 'doi:10.21418/G8', 'doi:10.25494/P6', 'doi:10.4246/10', 'doi:10.4246/CA', 'doi:10.4246/CW', 'doi:10.4246/UC', 'doi:10.5060/D2', 'doi:10.5060/D4', 'doi:10.5060/D8', 'doi:10.5062/F4', 'doi:10.5063/08', 'doi:10.5063/3X', 'doi:10.5063/5T', 'doi:10.5063/7P', 'doi:10.5063/9K', 'doi:10.5063/AA', 'doi:10.5063/BG', 'doi:10.5063/CF', 'doi:10.5063/F1', 'doi:10.5063/F7', 'doi:10.5063/G7', 'doi:10.5063/H7', 'doi:10.5063/K0', 'doi:10.5063/M0', 'doi:10.5063/NS', 'doi:10.5063/PR', 'doi:10.5063/QR', 'doi:10.5063/SJ', 'doi:10.5063/TH', 'doi:10.5063/VH', 'doi:10.5063/X9', 'doi:10.5063/Z8', 'doi:10.5065/D6', 'doi:10.6072/H0', 'doi:10.6075/J0', 'doi:10.6078/D1', 'doi:10.6078/J8', 'doi:10.6078/M7', 'doi:10.6080/K0', 'doi:10.6085/AA', 'doi:10.7280/S9', 'doi:10.7293/W2', 'doi:10.7297/X2', 'doi:10.7299/X7', 'doi:10.7928/H6', 'doi:10.7940/M3'

## Unique prefixes to process:
'doi:10.13022', 'doi:10.15782', 'doi:10.18118', 'doi:10.18739', 'doi:10.21224', 'doi:10.21228', 'doi:10.21229', 'doi:10.21418', 'doi:10.25494', 'doi:10.5062', 'doi:10.5065', 'doi:10.6072', 'doi:10.6075', 'doi:10.6080', 'doi:10.6085', 'doi:10.7280', 'doi:10.7293', 'doi:10.7297', 'doi:10.7299', 'doi:10.7928', 'doi:10.7940'
