### ISSUE TITLE
[DATA] Update DataCite Schema Records in prior version to Version 4.5 after notice period

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#767]
## Background
Following the notification of users on https://github.com/CDLUC3/ezid/issues/766 about our intent to update their DataCite schema records, we should proceed to update once the notice period has expired.

## Task List
- [x] 1. Verify completion of notice period from previous issue (#540)
- [x] 2. Test update process
- [x] 3. Execute full update process:
  - Use admin account to reprocess selected records
  - Apply `upgradeDcmsRecord` function from `datacite.py`
  - Follow [EZID reprocessing procedures](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/reprocess_ids.md)
- [x] 4. Verify sample of updated records

## Related Issues
- Part of https://github.com/CDLUC3/ezid/issues/540
- [#511](https://github.com/CDLUC3/ezid/issues/511) (Discussion of older version schema support)
