### ISSUE TITLE
[DATA] Queue Cleanup - SearchIndex

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#769]
## Data Task Type
Queue Cleanup - SearchIndex

## Describe the data task needed
As described in #723, we need to clean up the SearchIndex queue to address the successful status changed from "S" to "O", processing missed records from #394 #371.

## Task list
- [x] 1. Review records with status='S' created before  "2023-06-29 05:03:43" (Thursday 5am)/seq=9337226
- [x] 2. Update records with status='S' to status='O' (over 9m records)
- [x] 3. Process and delete over 9m records that had status changed from 'S' to 'O' 
- [x] 4. Process and delete over 5m records with success (status='O') or ignore (status='I') status missed as a result of a `bug in proc-cleanup-async-queues.py`.

## Expected outcome
SearchIndex queue cleaned of unnecessary records, including old 'S' status records and missed status 'O' records.

Status captured on 2024-10-14:
```
  "searchindexer": {
    "F": 54,
    "O": 5291658,
    "S": 9337175
  }
```

**Comment by jsjiang** [comment]
SearchIndex queue records was reduced from 14M to 368K after batch cleanup. See details here:

https://github.com/CDLUC3/ezid/issues/723#issuecomment-2477673711
