### ISSUE TITLE
[EPIC] Upgrade from DataCite schema 4.5 to 4.6

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#805]
DataCite's schema 4.6 is now public, so we need to upgrade EZID to support DOIs registered with this version of the schema.

**Requirements:**

- [x] Version 4.6 becomes the default schema version for new DataCite DOIs
- [x] Version 4.6 is supported for DataCite DOIs registered via both the UI and API
- [x] Version 4.6 is supported for XML registrations
- [x] Version 4.6 is supported in the batch-registration script
- [x] Existing DataCite DOIs that have older schema versions can be updated by users to incorporate the new elements from 4.6
- [ ] In the case of existing DataCite DOIs with older schema versions, users updating those DOIs (regardless of whether they are incorporating 4.6 elements or not) should not experience any compatibility errors when they make changes as long as the DOIs were registered with 4.x-compatible metadata. If the DOIs are not 4.x compatible, users will receive an error
- [x] Update Quick Start Guides for 4.6 updates

**Changes in version 4.6 that need to be reflected in EZID are as follows:**

[DataCite documentation](https://datacite-metadata-schema.readthedocs.io/en/4.6/introduction/version-update/)

- **Add "Award" and "Project" as allowed resource types** in the resourceTypeGeneral field. These values should be added to UI dropdowns where resourceTypeGeneral is used, including:
  - Resource type dropdown
  - Any other locations using resourceTypeGeneral

- **Add "CSTR" and "RRID" as allowed identifier types** in the relatedIdentifierType field. These values should be added to dropdowns where relatedIdentifierType is used, including:
  - Related identifier type dropdown

- **Add "Translator" as new contributor type** in the contributorType field. This value should be added to dropdowns where contributorType is used, including:
  - Contributor type dropdown

- **Add new relation type pair to Related Identifier - Relation Type**: "HasTranslation" and "IsTranslationOf"

- **Add new date type**: "Coverage"

**Key milestones**

- [x] Develop and test new schema support on dev
- [x] Develop and test new schema support on stage
- [x] Test new schema support on stage
- [x] Release on production
- [x] Communicate to users (via EZID-L) that new schema version is available

**Tests**
- [x] UI create DataCite record (advanced form) with/without required data fields
- [x] UI update Schema 4.x records
- [x] API create Schema 4.x records with/without required data fields
- [x] API update Schema 4.x records with/without required data fields
- [x] API create datacite.fieldname profile record
- [x] API update datacite.fieldname profile record
- [x] batch-registration script

**Deployment plan**

- [x] Create new migration file
- [x] Deploy the release code
- [x] Stop EZID
- [x] Apply the database migrations
- [x] Restart EZID

**Comment by jsjiang** [comment]
* Reviewed EZID documentation on [How to upgrade DataCite schema](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/how_to_upgrade_datacite_schema.md)
* Created branch 805_DataCite_4.6_upgrade
* downloaded DataCite 4.6 schema files

Updated schema files:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   datacite-contributorType-v4.xsd
        modified:   datacite-dateType-v4.xsd
        modified:   datacite-relatedIdentifierType-v4.xsd
        modified:   datacite-relationType-v4.xsd
        modified:   datacite-resourceType-v4.xsd
        modified:   datacite-titleType-v4.xsd
        modified:   ../metadata.xsd
```

**Comment by jsjiang** [comment]
Add "Award" and "Project" as allowed resource types in the resourceTypeGeneral field:
1. Added to the dropdown list - the `RESOURCE_TYPES` variable defined in `form_object.py`
2. Added to the identifier data model validation routine - the`resourceTypes` variable defined in `models/validation.py`

**Comment by jsjiang** [comment]
Add "Translator" as new contributor type in the contributorType field
* added to the dropdown list - the `CONTRIB_TYPES` defined in the `form_objects.py` file

**Comment by jsjiang** [comment]
Add new relation type pair to Related Identifier - Relation Type: "HasTranslation" and "IsTranslationOf"
* added to the dropdown list - the `RELATION_TYPES` defined in the `form_objects.py` file

**Comment by jsjiang** [comment]
Add new date type: "Coverage"
* added to the dropdown list - the `DATE_TYPES` defined in the `form_objects.py` file

**Comment by jsjiang** [comment]
**Question**: 
The `static_src/locale/fr_CA/LC-MESSAGES/django.po` file has message IDs for items in the `form_objects.py` file. Do we need to update this file and IDs when adding new values to the dropdown lists? 

Sample code: 

```
#: code/form_objects.py:41
msgid "Select a type of object"
msgstr ""

#: code/form_objects.py:41
msgid "Audiovisual"
msgstr ""

#: code/form_objects.py:42
msgid "Collection"
msgstr ""
...

#: code/form_objects.py:435
msgid "Select a type of contributor"
msgstr ""

#: code/form_objects.py:436
msgid "Contact Person"
msgstr ""

#: code/form_objects.py:437
msgid "Data Collector"
msgstr ""

**Comment by jsjiang** [comment]
Tag `test-datacite-4.6_v1` is on ezid-stg ready for testing

**Comment by jsjiang** [comment]
* Created database migration file
* created new tag `test-datacite-4.6_v2` and deployed on ezid-stg
* applied the migration to EZID-Dev (from my Mac) and EZID-STG (on ezidui-stg01)
* performed unit tests on my Mac

create the migration file:
```
python manage.py makemigrations ezidapp
Migrations for 'ezidapp':
  ezidapp/migrations/0007_alter_searchidentifier_searchableresourcetype.py
    - Alter field searchableResourceType on searchidentifier
  ```  

Apply the migration file:
```
python manage.py migrate
```

Unit tests
```
pytest --ds=settings.tests tests/
```

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam, tag `test-datacite-4.6_v2` is on eid-stg ready for testing DataCite 4.6 upgrade. Let me know if you notice issues.  Thank you!

**Comment by jsjiang** [comment]
* Replaced PDF documentation links with didrect DataCite links in the `/create/advanced` and `/demo/advanced` pages  
* Removed obsolete PDF files
* deployed tag `test-datacite-4.6_v4` on ezid-stg for testing

@adambuttrick Hi Adam, ezid-stg is ready for testing changes to the documentation links. The links appear in two pages: the create/advanced and demo/advanced. Please take a look. Thank you!

**Comment by adambuttrick** [comment]
@jsjiang All looks good to me!
