### ISSUE TITLE
[DATA] Register ARKs in EZID for UCB

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#815]
## Context

As described in https://github.com/CDLUC3/ezid/issues/601, UCB is looking to deprecate their ARK resolver and manage all of their ARKs using EZID. They've winnowed down their ARKs to the attached file, which need to be registered under their existing shoulder, 28722/bk.

## File
[20241206_UCB_ARKs.xlsx](https://github.com/user-attachments/files/18160113/20241206_UCB_ARKs.xlsx)

## Task list
- [x] 1. Register ARKs with in spreadsheet with provided metadata
- [x] 2. Testing
  - [x] Run test registration for small batch (5-10 records)
  - [x] Verify resolution for small batch
  - [x] Confirm records appear correctly in EZID
- [x] 3. Full Registration
  - [x] Execute registration for all records
  - [x] Generate report of successful/failed registrations
  - [x] Document any errors or issues encountered
- [x] 4. QA
  - [x] Verify random sample of registered ARKs resolve correctly
  - [x] Notify Berkeley Library team of completion

**Comment by jsjiang** [comment]
* Prefix `ark:/28722/bk` does not have an associated minter. So we need to create a minter for this prefix before minting identifiers under this prefix
* Both merritt (id=124) and ucblibrary (id=210) have access to this shoulder (has entries in the user_and_shoulders table)
* Currently there are 316,580 identifiers under this prefix
  * owners: merritt (id=124), ucblibrary (id=210) and ucm_libda (id=390)
    * question: The ucm_libda (id=390) account does not have a user and shoulder relationship. Why the user has identifiers under this shoulder?  
* sample identifier:
  * ark:/28722/bk000001t7t
  * ark:/28722/bk0000m7z8d

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam, 
There are a few things to resolve before we can mint ARKs for these items.
1. We do not have a script/command to add a minter to an existing shoulder. I will create a new script for this.
2. Which owner to use when creating ARKs for these items? Possible candidates are merritt (id=124) and ucblibrary (id=210).
3. There are 41 identifiers registered under this shoulder with user `ucm_libda` (owner_id=390) and group `ucmlibrary` (ownergroup_id=199). However, this owner and group do not have access to this shoulder. I don't know how these identifiers were created initially. The ucm-libda user shoulder have access (read and edit) to these identifiers. However, I don't think they can create new identifiers under this shoulder. We can grant shoulder access to this user/group if needed.

Jing

**Comment by adambuttrick** [comment]
The ucblibrary library account should be the owner. The issue with ucm_libda (owner_id=390) and group ucmlibrary (ownergroup_id=199) we should treat as a separate data issue, since all the provided data here is coming from (and thus should be managed by) ucblibrary.

**Comment by jsjiang** [comment]
* created `shoulder-create-minter` command in branch `815-create-minter-for-a-shoulder`
  * check for qualifications
    * shoulder exists
    * shoulder does not have a minter
    * the prefix (shoulder string) does not have an entry in the `minter` table
  * create a minter for the shoulder
* tested on ezid-stg
  * minter `ark:/28722/bk` does not exist
  * create a minter with prefix `ark:/28722/bk`
  * minter can mint identifiers

Testing log:
```
ezid@uc3-ezidui-stg01:08:21:09:~/tmp/ezid-jing-test$ python manage.py shoulder-mint ark:/28722/bk
impl.nog_sql.ezid_minter ERROR    ezid_minter - Minter Error: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ezid@uc3-ezidui-stg01:08:22:15:~/tmp/ezid-jing-test$ python manage.py shoulder-create-minter ark:/28722/bk
ezidapp.management.commands.shoulder-create-minter INFO     shoulder-create-minter - Getting shoulder ark:/28722/bk
ezidapp.management.commands.shoulder-create-minter INFO     shoulder-create-minter - A minter was created for Shoulder/Prefix: ark:/28722/bk
ezid@uc3-ezidui-stg01:08:23:23:~/tmp/ezid-jing-test$ python manage.py shoulder-mint ark:/28722/bk
ezidapp.management.commands.shoulder-mint INFO     shoulder-mint -     1 4w21
```

**Comment by jsjiang** [comment]
Use the `ezid-client-tool` to create identifiers:
* convert data file `20241206_UCB_ARKs.xlsx` to CSV file `20241206_UCB_ARKs.csv`
* remove header line from the CSV file
* create a configuration/mapping file
* run the `batch-register3.py` command to create identifiers

Config/mapping file config_ucb.txt
```
erc.what = $4
_target = $5
_status = public
```

**Comment by adambuttrick** [comment]
As adding a minter in EZID would require us to change the ID format, we've decided to switch to creating and will handle the adding new minter to a shoulder without in the new year.

**Comment by jsjiang** [comment]
Note: 
* we can use the `batch-register3.py` script in the `ezid-client-tools` repo to create identifiers.
* use the `create` for the operation option
* define a mapping file
* provide a input file in CSV format (remove the header line)
* use "@ucblibrary" as user and the admin password to create identifiers for the `ucblibrary` user account

Sample command:
```
batch-register3.py create mappings_config input_file.csv -c @ucblibrary:admin-password
```

**Comment by jsjiang** [comment]
* compiled data file and saved as `20241206_UCB_ARKs_create.csv`
  * added prefix `ark:/` to each ID field
  * removed unneeded data fields - only kept ID, title and URL fields
  * removed header line
  * file contains 893 lines/identifiers
* compiled a test data file `ucb_create_test.csv` with the first two lines from the input file
* created the mapping/configuration file `config_ucb.txt`
* creating test identifiers on ezid-prd finished with one error and one success:
```
1,ark:/28722/bk0005z0t6d,error: bad request - invalid identifier
2,ark:/28722/bk0005z0t7z,
```

config_ucb.txt
```
_id = $1
erc.what = $2
_target = $3
_status = public
```

Command for creating test identifiers on ezid-prd:
```
python batch-register3.py create config_ucb.txt ucb_create_test.csv -c @ucblibrary

1,ark:/28722/bk0005z0t6d,error: bad request - invalid identifier
2,ark:/28722/bk0005z0t7z,
```
Data and mapping/configuration files:

[ucb_create_test.csv](https://github.com/user-attachments/files/18213767/ucb_create_test.csv)
[config_ucb.txt](https://github.com/user-attachments/files/18213768/config_ucb.txt)
[20241206_UCB_ARKs_create.csv](https://github.com/user-attachments/files/18213769/20241206_UCB_ARKs_create.csv)

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam, I tried to create two identifiers on ezid-prd. One failed and one was successful. The metadata and resolver functions all look good to me. Can you take a look.

ID: ark:/28722/bk0005z0t7z
EZID link: https://ezid.cdlib.org/id/ark:/28722/bk0005z0t7z
EZID resolver link: https://ezid.cdlib.org/ark:/28722/bk0005z0t7z
Identifier as URL: https://n2t.net/ark:/28722/bk0005z0t7z
  
I am troubleshooting why creating `ark:/28722/bk0005z0t6d` had error. 

The full list of data file and the mapping/configuration file are attached to the above comment. We can run batch registration in prd when we feel comfortable. 

Jing

**Comment by adambuttrick** [comment]
@jsjiang Representation of the record looks correct and everything is resolving fine, so just keep us apprised of the your progress on the registration error and we can proceed with the batch registration.

**Comment by jsjiang** [comment]
It looks like the input file has a leading BOM ("EF BB BF") at the beginning of the file.

Workaround: Save the input file in "CSV" (not UTF-8 CSV) when converting the file from Excel xlsx) to CSV format.

ezid_access.log:172.30.47.21 - - [20/Dec/2024:09:49:20 -0800] "PUT /id/%EF%BB%BFark:/28722/bk0005z0t6d HTTP/1.1" 400 39 "-" "Python-urllib/3.11"

**Comment by jsjiang** [comment]
* Registered all 893 identifiers listed in file `20241206_UCB_ARKs.xlsx` in EZID Prd
* Verified a few records and they all resolving fine

```
python batch-register3.py create config_ucb.txt 20241206_UCB_ARKs_create.csv -c @ucblibrary
1,noid,error: bad request - invalid identifier
2,ark:/28722/bk0005z0t6d,error: bad request - identifier already exists
3,ark:/28722/bk0005z0t7z,error: bad request - identifier already exists
4,ark:/28722/bk0005z0t8h,
5,ark:/28722/bk0005z0t92,
6,ark:/28722/bk0005z0v0m,
7,ark:/28722/bk0005z0v15,
8,ark:/28722/bk0005z0v2q,
9,ark:/28722/bk0005z0v38,
10,ark:/28722/bk0005z0v4t,
... ...
888,ark:/28722/bk000713220,
889,ark:/28722/bk00071323j,
890,ark:/28722/bk000713243,
891,ark:/28722/bk00071325n,
892,ark:/28722/bk000713266,
893,ark:/28722/bk00071327r,
894,ark:/28722/bk000713289,
```

**Comment by adambuttrick** [comment]
@jsjiang Thanks! I'll notify UCB.

**Comment by jsjiang** [comment]
@adambuttrick HI Adam, can you do a spot checking. Thank you Jing

**Comment by adambuttrick** [comment]
I tested many at random and they all resolved.

**Comment by adambuttrick** [comment]
Notified UCB.
