### ISSUE TITLE
Berkeley DB migration to MySQL

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#87]

**Comment by jsjiang** [comment]
Tasks:
- [ ] Understand how Berkeley DB works
- [ ] Understand minter DB design
- [ ] Understand minter core concepts and algorithms
- [ ] Understand Shoulder minting workflow
- [ ] Understand Identifier minting workflow
- [ ] Design MySQL based minter algorithms
- [ ] Design minter tables in MySQL
- [ ] Create new minter tables in MySQL 
- [ ] Migrate Minter datasets to MySQL
- [ ] Modify EZID code to use MySQL for minting shoulders and identifiers
- [ ] Test minter migration

**Comment by jsjiang** [comment]
[Analysis document](https://docs.google.com/presentation/d/1xFOjSyZvrEg9gQxJ8bVs5GV2-PFNcehs2A-55NDKbPA/edit#slide=id.p)

**Comment by jsjiang** [comment]
Subtask tickets:
* #442 
* #428
